import { Inter } from "next/font/google";
import "./globals.css";
import "toastify-js/src/toastify.css";
import "bootstrap/dist/css/bootstrap.min.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Face Saver",
  description: "Generated by IF C IMK Kelompok 5",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
